### ISSUE TITLE
Current API and Laptop-App

### ISSUE THREAD

**Issue by bell07** [orbitaldecay/central_bank#2]
I think this is the beter place for development related diskussions.
At the first no worries about the API breaks, just let me know and I adjust my code.
Do you like to rename "transfer" to "do_transfer"?

Thanks again for the last changes. Now my next which list ;-)

- The history should contain the "trading partner" (from/to) and the transaction id. This way searching for will be possible.
`central_bank.do_transaction(to, string.format("Transfer from %s (#%d): '%s'", from, id, reason), amount)`
should be
`central_bank.do_transaction(to, from, id, reason, amount)` 
The texts visualization should be done if needed before output. (from or too can be determinated by amount sign)

- A player should be able to delete old history entries (`central_bank.do_clear_history(name, before_date)` ?

EDIT: about lua syntax:
`central_bank.transfer = function(from, to, amount, reason)`
more common is
`function central_bank.transfer(from, to, amount, reason)`

**Comment by orbitaldecay** [comment]
I'll rename transfer to do_transfer, add the applicable fields to the transaction records, and add a delete history function. Also, thanks for the tip on the Lua syntax.

**Comment by orbitaldecay** [comment]
Check it out now, I think you'll find the changes useful.

**Comment by bell07** [comment]
One thing: please add the "reason" to the history entry too.The other variables are all there ;-)

**Comment by orbitaldecay** [comment]
It's there, as "description" internally. You may also want to check out my market mod which depends on central_bank. libmarket could use a laptop ui as well!

**Comment by rubenwardy** [comment]
There's no need for the `do_`, really. Transfer is already a noun

**Comment by bell07** [comment]
My intention is to be able to have "raw data", not the "interpreted" description

**Comment by orbitaldecay** [comment]
Like inserting tables and other data? Perhaps a different field would be useful for meta data, as I was thinking the description field could be used for human readable stuff.

**Comment by orbitaldecay** [comment]
What is the advantage of adding that kind of support to the central_bank API versus leaving the string creation to the code which is utilizing the API? If there is data that is not currently being provided by the API that you need to build the strings, I'd rather just expose that.

**Comment by bell07** [comment]
I like the "leaving the string creation to the code which is utilizing the API" idea. All data is available now

**Comment by orbitaldecay** [comment]
Okay, cool :) Let me know if you need any other data or have any other ideas.

**Comment by orbitaldecay** [comment]
Also, perhaps it would be good just to show the first 20 characters or so of the description so users can leave notes easily for each other?

**Comment by bell07** [comment]
![image](https://user-images.githubusercontent.com/4731334/42712900-ab924c9e-86ed-11e8-80d7-b11a563bdcd9.png)

Show history and transfers are done. Should I setup a PR? It's an own mod called banking_app that I like to see in your modpack.

By the way, we need a bank logo that I can use as App-Icon in laptop launcher

**Comment by orbitaldecay** [comment]
I pulled it. Looks great! Perhaps we should consult the community for a logo?

**Comment by orbitaldecay** [comment]
I also added a set_history method to the API to allow deletion or editing of history

**Comment by bell07** [comment]
To ask community is a good idea.

I added a simple cleanup function : Clear older enties, remain the newest 50 in inbox. Maybe the parameter needs to be ajdusted or should be a setting.

Fixed big also in set_history

If you like you can pull it, I go sleep
